name: make check

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  make-check:
    strategy:
      matrix:
        runners:
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-latest
          - macos-15
          - macos-14
    runs-on: ${{ matrix.runners }}
    steps:
    - uses: actions/checkout@v4
    - name: make check
      run: cd src && make check

  make-check-freebsd:
    runs-on: ubuntu-latest
    name: make check FreeBSD
    steps:
    - uses: actions/checkout@v4
    - name: make check
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        run: |
          echo 'cc -O2 -Wall' > src/conf-cc
          echo 'cc -s' > src/conf-ld
          cd src && make check

  make-check-openbsd:
    runs-on: ubuntu-latest
    name: make check OpenBSD
    steps:
    - uses: actions/checkout@v4
    - name: make check
      uses: vmactions/openbsd-vm@v1
      with:
        usesh: true
        run: |
          echo 'cc -O2 -Wall' > src/conf-cc
          echo 'cc -s' > src/conf-ld
          cd src && make check

  make-check-netbsd:
    runs-on: ubuntu-latest
    name: make check NetBSD
    steps:
    - uses: actions/checkout@v4
    - name: make check
      uses: vmactions/netbsd-vm@v1
      with:
        usesh: true
        run: cd src && make check
